/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "welcome": [],
    "dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "cashregisters.index": [],
    "cashregisters.store": [],
    "cashregisters.show": [
        {
            "name": "module",
            "binding": "slug"
        }
    ],
    "cashregisters.update": [
        {
            "name": "module",
            "binding": "slug"
        }
    ],
    "cashregisters.destroy": [
        {
            "name": "module",
            "binding": "slug"
        }
    ],
    "workstations.index": [
        {
            "name": "module",
            "binding": "slug"
        }
    ],
    "workstations.store": [
        {
            "name": "module",
            "binding": "slug"
        }
    ],
    "workstations.update": [
        {
            "name": "workstation",
            "binding": "id"
        }
    ],
    "workstations.destroy": [
        {
            "name": "workstation",
            "binding": "id"
        }
    ],
    "employees.index": [
        {
            "name": "module",
            "binding": "slug"
        }
    ],
    "employees.update": [
        {
            "name": "employee",
            "binding": "id"
        }
    ],
    "employees.updateDragAndDrop": [],
    "employees.destroy": [
        {
            "name": "employee",
            "binding": "id"
        }
    ],
    "categories.index": [
        {
            "name": "module",
            "binding": "slug"
        }
    ],
    "categories.store": [
        {
            "name": "module",
            "binding": "slug"
        }
    ],
    "categories.update": [
        {
            "name": "category",
            "binding": "id"
        }
    ],
    "categories.updateDragAndDrop": [],
    "categories.destroy": [
        {
            "name": "category",
            "binding": "id"
        }
    ],
    "dishes.index": [
        {
            "name": "module",
            "binding": "slug"
        }
    ],
    "dishes.store": [
        {
            "name": "module",
            "binding": "slug"
        }
    ],
    "dishes.update": [
        {
            "name": "dish",
            "binding": "id"
        }
    ],
    "dishes.destroy": [
        {
            "name": "dish",
            "binding": "id"
        }
    ],
    "products.index": [
        {
            "name": "module",
            "binding": "slug"
        }
    ],
    "products.store": [
        {
            "name": "module",
            "binding": "slug"
        }
    ],
    "products.update": [
        {
            "name": "product",
            "binding": "id"
        }
    ],
    "products.updateDragAndDrop": [],
    "products.destroy": [
        {
            "name": "product",
            "binding": "id"
        }
    ],
    "transactions.index": [
        {
            "name": "module",
            "binding": "slug"
        }
    ],
    "transactions.destroy": [
        {
            "name": "transaction",
            "binding": "id"
        }
    ],
    "avatar.upload": [],
    "poster.upload": [],
    "picture-product.upload": [],
    "picture-dish.upload": [],
    "cashregister.index": [],
    "cashregister.store": [],
    "employee-profil.index": [],
    "avatar-employee.upload": [],
    "customers.login": [],
    "customers.register": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token"
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id"
        },
        {
            "name": "hash"
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "employees.login": [
        {
            "name": "module",
            "binding": "slug"
        },
        {
            "name": "code"
        }
    ],
    "employees.logout": [],
    "employees.register": [
        {
            "name": "module",
            "binding": "slug"
        }
    ],
    "employees.regenerate": [
        {
            "name": "employee",
            "binding": "id"
        }
    ]
}
}
export {};
